version: "2.4"
services:
  app:
    container_name: ${APP_NAME}
    image: golang:1.14
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MAPS_API_KEY:

  db:
    container_name: ${APP_NAME}_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

# networks:
#   net:

volumes:
  db_data:
