version: "2.4"
services:
  app:
    container_name: ${APP_NAME}
    image: ${APP_NAME}:latest
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MAPS_API_KEY:
      GIN_MODE:
    ports:
      - 8080:8080

  db:
    container_name: ${APP_NAME}_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
    ports:
      - 13306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

volumes:
  db_data:
