version: "2.4"
services:
  # app:
  #   image: alpine:3.11
  db:
    container_name: ${APP_NAME}_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - 0:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

# networks:
#   net:

volumes:
  db_data:
